## Travis CI Integration

language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild testApplication/testApplication.sln
  - nunit-console testApplication/bin/Debug/components.dll
